name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # 升級到支援度更好的 v4
        with:
          version: 9 # 強制使用最新主要的 v9 版本

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        # 使用 --no-frozen-lockfile 繞過 Catalog 引起的解析錯誤
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v4
